blank_issues_enabled: true
contact_links:
  - name: ğŸ“š Documentation
    url: https://vinicunca.dev/
    about: Check the documentation for usage of Akar.
  - name: ğŸ—¨ï¸ Discord
    url: https://chat.vinicunca.dev/
    about: Join the Vinicunca Discord server.
