name: Deploy Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'packages/**'
      - Dockerfile
      - .github/workflows/deploy-docs.yaml

env:
  WEB_SERVICE_NAME: akar-docs
  GOOGLE_CLOUD_REGION: asia-southeast1

jobs:
  prepare:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    outputs:
      GOOGLE_CLOUD_PROJECT_ID: ${{ steps.auth.outputs.GOOGLE_CLOUD_PROJECT_ID }}
      WEB_IMAGE_NAME: ${{ steps.auth.outputs.WEB_IMAGE_NAME }}
      WORKLOAD_IDENTITY_POOL_ID: ${{ steps.auth.outputs.WORKLOAD_IDENTITY_POOL_ID }}

    steps:
      - name: Determine auth variables
        id: auth
        run: |
          GOOGLE_CLOUD_PROJECT_ID=akar-docs
          echo "WORKLOAD_IDENTITY_POOL_ID=projects/643124329244/locations/global/workloadIdentityPools/github-action-pool/providers/github-actions-provider" >> "$GITHUB_OUTPUT"

          echo "GOOGLE_CLOUD_PROJECT_ID=${GOOGLE_CLOUD_PROJECT_ID}" >> "$GITHUB_OUTPUT"

          echo "WEB_IMAGE_NAME=${{ env.GOOGLE_CLOUD_REGION }}-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT_ID}/apps/${WEB_SERVICE_NAME}:${{ github.sha }}" >> "$GITHUB_OUTPUT"
  deploy:
    name: Deploy Docs to Google Cloud Run
    runs-on: ubuntu-latest

    needs: prepare

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ needs.prepare.outputs.WORKLOAD_IDENTITY_POOL_ID }}
          service_account: 'github-actions@${{ needs.prepare.outputs.GOOGLE_CLOUD_PROJECT_ID }}.iam.gserviceaccount.com'

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker ${{ env.GOOGLE_CLOUD_REGION }}-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -f Dockerfile -t ${{ needs.prepare.outputs.WEB_IMAGE_NAME }} .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push ${{ needs.prepare.outputs.WEB_IMAGE_NAME }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.WEB_SERVICE_NAME }}
          region: ${{ env.GOOGLE_CLOUD_REGION }}
          image: ${{ needs.prepare.outputs.WEB_IMAGE_NAME }}
          flags: --allow-unauthenticated --memory=512Mi --cpu=1 --min-instances=0 --max-instances=5 --concurrency=80
